#!/usr/bin/python2.7

import sys
import logging
import hashlib
import database as db

import index
import pdfscrape
import arxiv
import crossref

logging.basicConfig(level=logging.DEBUG)

total = 0
unidentified = 0

def scrape_pdf(fname):
        global total, unidentified
        metad = pdfscrape.find_ids(f)
        doi = metad.get('doi')
        arxiv_id = metad.get('arxiv_id')

        if doi:
                logging.debug('DOI of %s is %s' % (f, doi))
                m = crossref.lookup_doi(doi)
                if m:
                        metad['_id'] = 'doi:%s' % doi
                        metad.update(m)
                else:
                        logging.info('Failed to get crossref metadata for %s' % f)

        elif arxiv_id:
                logging.debug('arXiv ID of %s is %s' % (f, arxiv_id))
                m = arxiv.lookup_arxiv(arxiv_id)
                if m:
                        metad['_id'] = 'arxiv:%s' % arxiv_id
                        metad.update(m)
                else:
                        logging.info('Failed to get arXiv metadata for %s' % f)

        else:
                unidentified += 1
                logging.info('Could not identify %s' % f)

        total += 1
        return metad

import traceback
files = sys.argv[1:]
for f in files:
        h = hashlib.md5()
        h.update(open(f).read())
        md5 = h.hexdigest()

        ref = None
        try:
                ref = scrape_pdf(f)
        except Exception as e:
                logging.warn('Error processing %s: %s' % (f, e))
                logging.debug(traceback.format_exc())
                continue

        if 'title' not in ref or 'authors' not in ref:
                logging.warn('Insufficient metadata for %s' % f)
                continue

        dbref = index.find_ref(ref)
        refid = None
        if dbref is None:
                refid = db.refs.save(ref)
        else:
                refid = dbref['_id']

        file = db.documents.get(md5)
        if file is None:
                file = {
                        '_id': md5,
                        'md5': md5,
                        'ref': refid,
                        'filename': f
                }
                db.docs.save(file)
        elif file['ref'] != refid:
                logging.warn('%s (md5=%s): existing file %s in database already already assigned to ref %s' %
                             (f, md5, file['filename'], ref['_id']))
        else:
                logging.info('%s (md5=%s): File already associated with ref %s' %
                             (f, md5, refid))

if total > 0:
        logging.info('Processed %d files, %d unidentified (identified %3.1f%%)' %
                     (total, unidentified, 100.*(total-unidentified)/total))

