#!/usr/bin/python2.7

import sys
import logging
import hashlib
import pymongo

import index
import pdfscrape
import arxiv
import crossref

db = pymongo.Connection().refs

logging.basicConfig(level=logging.DEBUG)

total = 0
unidentified = 0

def scrape_pdf(fname):
        global total, unidentified
        metad = {}
        metad.update(metadata_extract.find_metadata(f))
        doi = metad.get('doi')
        arxiv_id = metad.get('arxiv_id')

        if doi:
                logging.debug('DOI of %s is %s' % (f, doi))
                m = crossref.lookup_doi(doi)
                m['_id'] = 'doi:%s' % doi
                if m:
                        metad.update(m)
                else:
                        logging.info('Failed to get crossref metadata for %s' % f)

        elif arxiv_id:
                logging.debug('arXiv ID of %s is %s' % (f, arxiv_id))
                m = arxiv.get_metadata(arxiv_id)
                m['_id'] = 'arxiv:%s' % arxiv_id
                if m:
                        metad.update(m)
                else:
                        logging.info('Failed to get arXiv metadata for %s' % f)

        else:
                unidentified += 1
                logging.info('Could not identify %s' % f)

        total += 1
        return metad

files = sys.argv[1:]
for f in files:
        h = hashlib.md5()
        h.update(open(f).read())
        md5 = h.hexdigest()

        ref = None
        try:
                ref = scrape_file(f)
        except Exception as e:
                logging.warn('Error processing %s: %s' % (f, e))

        dbref = index.find_ref(db, ref)
        refid = None
        if dbref is None:
                refid = db.refs.save(dbref)
        else:
                refid = dbref['_id']

        file = db.files.find_one({'md5': md5})
        if file is None:
                file = {
                        '_id': md5
                        'md5': md5,
                        'ref': refid,
                        'filename': f
                }
                db.files.save(file)
        elif file['ref'] != refid:
                logging.warn('While processing %s (md5=%s): existing file %s in database already already assigned to ref %s' %
                             (f, md5, file['filename'], ref['_id']))

logging.info('Processed %d files, %d unidentified (identified %3.1f%%)' %
             (total, unidentified, 100.*(total-unidentified)/total))

